In [1]:
import pandas as pd
import numpy as np

In [45]:
df = pd.read_csv('/content/drive/My Drive/ML Insternship/game_knn.csv')
df


Name  Age Gender     Sport
0    A   32      M  Football
1    B   40      M   Neither
2    C   16      F   Cricket
3    D   34      F   Cricket
4    E   55      M   Neither
5    F   40      M   Cricket
6    G   20      F   Neither
7    H   15      M   Cricket
8    I   55      F  Football
9    J   15      M  Football

In [46]:
from sklearn.preprocessing import LabelEncoder

In [52]:
le = LabelEncoder()
label = le.fit_transform(df['Gender'])


In [53]:
label

array([1, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [54]:
df

Name  Age  Gender     Sport
0    A   32       1  Football
1    B   40       1   Neither
2    C   16       0   Cricket
3    D   34       0   Cricket
4    E   55       1   Neither
5    F   40       1   Cricket
6    G   20       0   Neither
7    H   15       1   Cricket
8    I   55       0  Football
9    J   15       1  Football

In [55]:
df = df.drop('Gender', axis='columns')
df

Name  Age     Sport
0    A   32  Football
1    B   40   Neither
2    C   16   Cricket
3    D   34   Cricket
4    E   55   Neither
5    F   40   Cricket
6    G   20   Neither
7    H   15   Cricket
8    I   55  Football
9    J   15  Football

In [56]:
df.insert(2,'Gender', label)
df

Name  Age  Gender     Sport
0    A   32       1  Football
1    B   40       1   Neither
2    C   16       0   Cricket
3    D   34       0   Cricket
4    E   55       1   Neither
5    F   40       1   Cricket
6    G   20       0   Neither
7    H   15       1   Cricket
8    I   55       0  Football
9    J   15       1  Football

In [62]:
x = df.iloc[:, 1:3].values
x

array([[32,  1],
       [40,  1],
       [16,  0],
       [34,  0],
       [55,  1],
       [40,  1],
       [20,  0],
       [15,  1],
       [55,  0],
       [15,  1]])

In [63]:
y = df.iloc[:, 3]
y

0    Football
1     Neither
2     Cricket
3     Cricket
4     Neither
5     Cricket
6     Neither
7     Cricket
8    Football
9    Football
Name: Sport, dtype: object

In [64]:
y = le.fit_transform(y)
y

array([1, 2, 0, 0, 2, 0, 2, 0, 1, 1])

In [65]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import cross_val_score

classifier = KNeighborsClassifier(n_neighbors=3, metric='euclidean')

In [66]:
classifier.fit(x,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [67]:
y_pred = classifier.predict(x)

In [68]:
y_pred

array([0, 0, 0, 0, 2, 0, 0, 0, 2, 0])

In [69]:
y

array([1, 2, 0, 0, 2, 0, 2, 0, 1, 1])

In [70]:
cm = confusion_matrix(y,y_pred)
cm

array([[4, 0, 0],
       [2, 0, 1],
       [2, 0, 1]])

In [71]:
acc = accuracy_score(y,y_pred)*100
acc

50.0

In [72]:
x_new = np.array([[5,0]])

In [73]:
prediction = classifier.predict(x_new)
prediction

array([0])